### ISSUE TITLE
Doesn't work with ObjectId,  Doesn't work with undefined

### ISSUE THREAD

**Issue by mkrn** [mirek/node-rus-diff#7]
Hi I noticed if object contain ObjectId it would produce an error (from node-json-hash)  "Unsupported type"

Also, if it's undefined in an object then it would produce an Uncaught error in node-json-hash too.

I'm posting it here because technically json can't have ObjectId or undefined, but node-rus-diff can accept any object..

Here's what you can do to test:
```
var ObjectID = require("bson/lib/bson/objectid").ObjectID;
var obj = {
  _id: ObjectID(),
  somevar: "someval",
  someothervar: undefined
};
diff.diff(obj, {});
```

Otherwise the library is great! Hugely usable, thanks!

**Comment by cdupoiron** [comment]
Hey !
@mkrn Did you find a way arround this problem?

**Comment by mirek** [comment]
Please check v1.0.0, it should be fine.
