### ISSUE TITLE
Improve using in client-side by removing dependency in crypto

### ISSUE THREAD

**Issue by mkrn** [mirek/node-rus-diff#8]
Crypto module when pulled in to client-side build with browserify probably takes up 1+ Mb which is unfortunate.  

Are there alternatives that you can think of? I can help implementing those

Note: dependency is in node-json-hash

Thanks

**Comment by mirek** [comment]
Hi, ok I'll try to fix that.

**Comment by mirek** [comment]
This should be ok now.
